"""Let the paper and its supplement cite each other's numbers.

The two documents compile separately, so a ``\\ref`` in one to a label in the
other has nothing to resolve against, and the usual workarounds either hard-code
the numbers into the prose or require the other document's ``.aux`` to be present
at compile time.  Neither survives editing well, and the second does not survive
Overleaf, which compiles one root document at a time.

This script takes the third route.  It reads both ``.aux`` files from a local
build, and writes, for each document, a small file of ``\\newlabel`` entries for
the labels that live only in the other one.  ``sections/preamble.tex`` inputs the
appropriate file, so ``\\ref`` and ``\\Cref`` work in both directions with no
build-order dependency at all: the generated files are ordinary source, checked
in and uploaded like any other.

Run it after a local build, and rerun it whenever the numbering changes.  The
prose keeps semantic labels either way.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# ``\newlabel{key}{{...}}`` with an arbitrarily nested second argument.
LABEL = re.compile(r"\\newlabel\{([^}]+)\}\{")


def _entries(aux: Path) -> dict[str, str]:
    """Every ``\\newlabel`` in an aux file, keyed by label, value the full line."""

    text = aux.read_text(encoding="utf-8", errors="replace")
    out: dict[str, str] = {}
    for match in LABEL.finditer(text):
        key = match.group(1)
        # Copy the balanced second argument verbatim, so whatever hyperref put
        # there survives untouched.
        start = match.end() - 1
        depth, index = 0, start
        while index < len(text):
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
                if depth == 0:
                    break
            index += 1
        if depth != 0:
            continue
        # A sub-label such as ``key@cref`` belongs with its parent.
        out[key] = f"\\newlabel{{{key}}}{text[start:index + 1]}"
    return out


def _write(target: Path, entries: dict[str, str], *, source: str, own: set[str]) -> int:
    wanted = {key: line for key, line in entries.items() if key not in own}
    body = [
        "% Generated by scripts/build_cross_references.py -- do not edit.",
        f"% Labels defined in {source}, made visible to this document so that a",
        "% cross-document \\ref resolves without compiling the other file.",
        "\\makeatletter",
    ]
    for key in sorted(wanted):
        body.append(wanted[key])
    body += ["\\makeatother", ""]
    target.write_text("\n".join(body), encoding="utf-8")
    return len(wanted)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", type=Path, default=Path("C:/vcam_build"))
    parser.add_argument("--manuscript", type=Path, default=ROOT / "manuscript")
    args = parser.parse_args()

    main_aux = args.build / "main.aux"
    supp_aux = args.build / "supplement.aux"
    for path in (main_aux, supp_aux):
        if not path.exists():
            raise SystemExit(f"missing {path}; build both documents first")

    main_labels = _entries(main_aux)
    supp_labels = _entries(supp_aux)

    n_supp = _write(
        args.manuscript / "sections" / "xref-supplement.tex",
        supp_labels,
        source="supplement.tex",
        own=set(main_labels),
    )
    n_main = _write(
        args.manuscript / "sections" / "xref-main.tex",
        main_labels,
        source="main.tex",
        own=set(supp_labels),
    )
    print(f"sections/xref-supplement.tex: {n_supp} labels")
    print(f"sections/xref-main.tex: {n_main} labels")


if __name__ == "__main__":
    main()
